local_costmap:
  global_frame: map
  robot_base_frame: dummy #base_link
  update_frequency: 20.0
  publish_frequency: 20.0
  static_map: false
  rolling_window: true
  width: 4.2
  height: 4.2 #6
  resolution: 0.05
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
